### ISSUE TITLE
vana özelliklerindeki ocak borusu ayarla butonu evsel ocak özelliklerinde olması

### ISSUE THREAD

**Issue by fatihhilmi** [ifenerji/customer#2]
tüm cihaz vanalarında bu özelliğin görünmesi ve tıklanması durumunda problemler yaşanabiliryor
sadece evsel ocak cihazında bu özellik kullanılması mantıklı olacaktır

![image](https://user-images.githubusercontent.com/33824444/35429920-29df21da-0287-11e8-9370-0f6ecb153825.png)

![image](https://user-images.githubusercontent.com/33824444/35429964-5a0322b2-0287-11e8-9167-48a2ccea49be.png)

**Comment by fatihhilmi** [comment]
customer tarafına taşındı

**Comment by halilozer** [comment]
Ticari cihazların coğunda kullanılan bir özellik, kaldırmak mantıklı değil @fatihhilmi müşteri kendi isteğiyle tıklıyorsa onun sorumluluğunda olan bişey yanlış çapada tıklayabilir mesela

**Comment by fatihhilmi** [comment]
kaynaklı birleştirme yapılacak tüm tesisatlarda DN20 den küçük boru çapı kullanılmamalıdır. (Bknz. şartname sayfa 39)
yani bu durumda sadece evsel ocaklarda ve sobalarda dn15 boru ve vana kullanımına izin vardır.

Bu durumda soba özelliklerine de soba borusu ayarla butonu eklenebilir

**Comment by ikayar** [comment]
taşındı
