### ISSUE TITLE
mobil imza tanımlı olmayan firmalarda buton sönük olsun

### ISSUE THREAD

**Issue by fatihhilmi** [ifenerji/customer#3]
firmalar e-imza ve mobil imza butonları karıştırıyorlar
mobil imza desteği olmadığı halde firmalar mobil imza butonuna tıklıyorlar.
gelen mühendis cep telefonu kayıtlı değil uyarısıyla alakalı bizi arıyorlar

bu buton mobil imza desteği almayan firmalarda tıklanabilir olmasın.

**Comment by ikayar** [comment]
ifenerji/webcad altına taşınmıştır.
