### ISSUE TITLE
hesap işlemlerinde sigorta poliçelerin listelemesi

### ISSUE THREAD

**Issue by fatihhilmi** [ifenerji/customer#4]
gasline nin aşagıdaki modelde listelemesi mevcuttur.Webcad üzerinden oluşturulan poliçelerin listelenmesi sağlanmalıdır. ek poliçe ve proje poliçelendirilmesi ayrı sıralanmalı yada ayrı listelenmeli gibi detaylara dikkat edilmelidir.

![image](https://user-images.githubusercontent.com/33824444/35815750-4fdd2dd4-0aaa-11e8-9754-7b20ddf929d1.png)

**Comment by ikayar** [comment]
taşındı
