### ISSUE TITLE
tesisat ve izometri modunda mg anot yazısının taşınması

### ISSUE THREAD

**Issue by fatihhilmi** [ifenerji/customer#5]
Mg Anot 2lb açıklamasının tesisat ve izomerik karışıklıkları gidermek adına taşınmasına izin verilmelidir

![image](https://user-images.githubusercontent.com/33824444/35869899-4d7b4cca-0b71-11e8-919b-01b6c46b5986.png)
![image](https://user-images.githubusercontent.com/33824444/35869918-5d2a47e8-0b71-11e8-86cd-d86c408a21eb.png)

**Comment by ikayar** [comment]
taşındı.
