### ISSUE TITLE
kolon branşmanlarının otamatik eklenmesi

### ISSUE THREAD

**Issue by fatihhilmi** [ifenerji/customer#6]
kolon projesi çizdikten sonra kutu üzerinde sağ tıklayınca " tüm tüketim vanalarını ekle " şeklinde buton
firma isteğidir. 

![image](https://user-images.githubusercontent.com/33824444/35983981-65c429ac-0d04-11e8-9cb4-7211444f9efa.png)

bu buton boştaki kolon hatlarına otomatik olarak tüketim vanası ekleme özelliğinde olacaktır.

bu özelliğin sayaç ve vana ekli olan hatlara müdale olası engellenmelidir

**Comment by ikayar** [comment]
taşındı
