### ISSUE TITLE
kolon projesinde iç tesisatların silinmesi

### ISSUE THREAD

**Issue by fatihhilmi** [ifenerji/customer#7]
genelde kolon ile beraber çizilmiş ve kolon projesinde tadilat yapmak gerektiğinde iç tesisatı (daireleri) silmek zahmetli oluyor.
![image](https://user-images.githubusercontent.com/33824444/35984427-776ba120-0d05-11e8-836e-7a752160f196.png)

kutu üzerine sağ tıklayın " daire tesisatını sil " şeklinde buton eklenmesi tıklandığında kolon üzerindeki iç tesisatı temizleyip sayacı silip sayaç vanasını tüketim vanası olarak değiştirilmesi sağlanmalıdır. sayaç üzerinde daire no mevcut ise tüketim vanası özelliklerindeki birim no kısmına yazılmasını sağlayacak bir komut müşteri isteğidir.

**Comment by ikayar** [comment]
taşındı
